### ISSUE TITLE
Crashing with the latest commit.

### ISSUE THREAD

**Issue by ReddestDream** [PoomSmart/EmojiPort-Legacy#1]
Note: I am posting this here instead of on Twitter so that I do not wake you since there is a rather large time zone difference between us.

So, after this last commit, I keep getting crashing as soon as I try to open the emoji keyboard.

EmojiLayout is not the problem. It works perfectly with my build made from the last commit.

I built this latest commit with Xcode 6.3.1's command line tools and the OS 8.3 SDK, and I installed Theos by following these instructions:

http://iphonedevwiki.net/index.php/Theos/Setup

I got larger number of compiler errors than usual with this build:

Tweak.xm:368:12: warning: unused variable 'displayFrame' [-Wunused-variable]
                                CGRect displayFrame = inputGeometry.disp...
                                       ^
Tweak.xm:438:8: warning: instance method
      '-emoji83_positionFixForKeyplane:key:withFrame:' not found (return type
      defaults to 'id') [-Wobjc-method-access]
        [self emoji83_positionFixForKeyplane:keyplane key:key withFrame:...
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lukas/Emoji83/Emoji.h:84:12: note: receiver is instance of class declared
      here
@interface UIKBKeyView : UIView {
           ^
Tweak.xm:446:8: warning: instance method
      '-emoji83_positionFixForKeyplane:key:withFrame:' not found (return type
      defaults to 'id') [-Wobjc-method-access]
        [self emoji83_positionFixForKeyplane:keyplane key:key withFrame:NULL];
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lukas/Emoji83/Emoji.h:84:12: note: receiver is instance of class declared
      here
@interface UIKBKeyView : UIView {
           ^
Tweak.xm:888:38: warning: class method '+layoutClassForCurrentInputMode' not
      found (return type defaults to 'id') [-Wobjc-method-access]
        Class layoutClass = [UIKeyboardImpl layoutClassForCurrentInputMode];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tweak.xm:4:18: warning: unused function 'emojiFromUnicode' [-Wunused-function]
static NSString *emojiFromUnicode(UniChar *unicode)
                 ^
Tweak.xm:59:13: warning: unused function 'addFlagEmojis' [-Wunused-function]
static void addFlagEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:71:13: warning: unused function 'addFamilyEmojis' [-Wunused-function]
static void addFamilyEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:156:13: warning: unused function 'addVulcanEmojis' [-Wunused-function]
static void addVulcanEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:161:13: warning: unused function 'addDiverseEmojis1'
      [-Wunused-function]
static void addDiverseEmojis1(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:174:13: warning: unused function 'addDiverseEmojis3'
      [-Wunused-function]
static void addDiverseEmojis3(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:196:13: warning: unused function 'addMMWWEmojis' [-Wunused-function]
static void addMMWWEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:204:13: warning: unused function 'updateCategory' [-Wunused-function]
static void updateCategory(UIKeyboardEmojiCategory *category, int type)
            ^
12 warnings generated.
Tweak.xm:368:12: warning: unused variable 'displayFrame' [-Wunused-variable]
                                CGRect displayFrame = inputGeometry.disp...
                                       ^
Tweak.xm:438:8: warning: instance method
      '-emoji83_positionFixForKeyplane:key:withFrame:' not found (return type
      defaults to 'id') [-Wobjc-method-access]
        [self emoji83_positionFixForKeyplane:keyplane key:key withFrame:...
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lukas/Emoji83/Emoji.h:84:12: note: receiver is instance of class declared
      here
@interface UIKBKeyView : UIView {
           ^
Tweak.xm:446:8: warning: instance method
      '-emoji83_positionFixForKeyplane:key:withFrame:' not found (return type
      defaults to 'id') [-Wobjc-method-access]
        [self emoji83_positionFixForKeyplane:keyplane key:key withFrame:NULL];
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lukas/Emoji83/Emoji.h:84:12: note: receiver is instance of class declared
      here
@interface UIKBKeyView : UIView {
           ^
Tweak.xm:888:38: warning: class method '+layoutClassForCurrentInputMode' not
      found (return type defaults to 'id') [-Wobjc-method-access]
        Class layoutClass = [UIKeyboardImpl layoutClassForCurrentInputMode];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tweak.xm:4:18: warning: unused function 'emojiFromUnicode' [-Wunused-function]
static NSString *emojiFromUnicode(UniChar *unicode)
                 ^
Tweak.xm:59:13: warning: unused function 'addFlagEmojis' [-Wunused-function]
static void addFlagEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:71:13: warning: unused function 'addFamilyEmojis' [-Wunused-function]
static void addFamilyEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:156:13: warning: unused function 'addVulcanEmojis' [-Wunused-function]
static void addVulcanEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:161:13: warning: unused function 'addDiverseEmojis1'
      [-Wunused-function]
static void addDiverseEmojis1(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:174:13: warning: unused function 'addDiverseEmojis3'
      [-Wunused-function]
static void addDiverseEmojis3(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:196:13: warning: unused function 'addMMWWEmojis' [-Wunused-function]
static void addMMWWEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:204:13: warning: unused function 'updateCategory' [-Wunused-function]
static void updateCategory(UIKeyboardEmojiCategory *category, int type)
            ^
12 warnings generated.
Tweak.xm:368:12: warning: unused variable 'displayFrame' [-Wunused-variable]
                                CGRect displayFrame = inputGeometry.disp...
                                       ^
Tweak.xm:438:8: warning: instance method
      '-emoji83_positionFixForKeyplane:key:withFrame:' not found (return type
      defaults to 'id') [-Wobjc-method-access]
        [self emoji83_positionFixForKeyplane:keyplane key:key withFrame:...
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lukas/Emoji83/Emoji.h:84:12: note: receiver is instance of class declared
      here
@interface UIKBKeyView : UIView {
           ^
Tweak.xm:446:8: warning: instance method
      '-emoji83_positionFixForKeyplane:key:withFrame:' not found (return type
      defaults to 'id') [-Wobjc-method-access]
        [self emoji83_positionFixForKeyplane:keyplane key:key withFrame:NULL];
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lukas/Emoji83/Emoji.h:84:12: note: receiver is instance of class declared
      here
@interface UIKBKeyView : UIView {
           ^
Tweak.xm:888:38: warning: class method '+layoutClassForCurrentInputMode' not
      found (return type defaults to 'id') [-Wobjc-method-access]
        Class layoutClass = [UIKeyboardImpl layoutClassForCurrentInputMode];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tweak.xm:4:18: warning: unused function 'emojiFromUnicode' [-Wunused-function]
static NSString *emojiFromUnicode(UniChar *unicode)
                 ^
Tweak.xm:59:13: warning: unused function 'addFlagEmojis' [-Wunused-function]
static void addFlagEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:71:13: warning: unused function 'addFamilyEmojis' [-Wunused-function]
static void addFamilyEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:156:13: warning: unused function 'addVulcanEmojis' [-Wunused-function]
static void addVulcanEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:161:13: warning: unused function 'addDiverseEmojis1'
      [-Wunused-function]
static void addDiverseEmojis1(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:174:13: warning: unused function 'addDiverseEmojis3'
      [-Wunused-function]
static void addDiverseEmojis3(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:196:13: warning: unused function 'addMMWWEmojis' [-Wunused-function]
static void addMMWWEmojis(UIKeyboardEmojiCategory *emojiObject)
            ^
Tweak.xm:204:13: warning: unused function 'updateCategory' [-Wunused-function]
static void updateCategory(UIKeyboardEmojiCategory *category, int type)
            ^
12 warnings generated.

I still got a finished build; however, so I tried to use it.

This is the relevant section of the syslog:

Thu Apr 23 15:38:22 2015: SpringBoard (com.apple.springboard): **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 10 beyond bounds [0 .. 3]'
**\* First throw call stack:
(0x183f3a59c 0x1946980e4 0x183e1f62c 0x188b2f5b0 0x188db993c 0x188b2e17c 0x1887f9e70 0x1887f2160 0x1887f0db0 0x1887f089c 0x188712930 0x188a6bd18 0x188a6b86c 0x188a6c85c 0x1888b5bb0 0x1888a9c78 0x1888a8c0c 0x1888a8594 0x188714950 0x1888a4d0c 0x1888a4ac4 0x1022e7bb4 0x106163014 0x18872035c 0x1887198b0 0x1886ecfa8 0x18898bf58 0x1886eb510 0x183ef29ec 0x183ef1c90 0x183eefd40 0x183e1d0a4 0x18cfbf5a4 0x1887523c0 0x1000f6864 0x194d06a08)
Thu Apr 23 15:38:22 2015: ReportCrash (Crash Reporter): task_set_exception_ports(B07, 400, 1503, 0, 0) failed with error (4: (os/kern) invalid argument)
Thu Apr 23 15:38:22 2015: ReportCrash (Crash Reporter): ReportCrash acting against PID 4350
Thu Apr 23 15:38:22 2015: ReportCrash (Crash Reporter): Formulating crash report for process SpringBoard[4350]

The crash was a SIGABRT and Emoji83 was not implicated as a suspect by CrashReporter.

I tried deleting the Emoji Preferences at /User/Library/Preferences, but this didn't resolve the crashing.

Thanks! ^_^

**Comment by PoomSmart** [comment]
Fixed.
