### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by kewachan** [PoomSmart/EmojiPort-Legacy#12]
some flags can't be displayed in the keyboard, it shows a square with a letter... 

ios 8.1.2, emoji83 1.0-54, emojilayout 1.0-20

**Comment by PoomSmart** [comment]
Show me screenshot.

**Comment by Skylerk99** [comment]
http://i.imgur.com/hJcKqSa.png

**Comment by browno01** [comment]
You need the iOS 9 emoji font to see those.

On 16 June 2015 at 15:41, Skylerk99 notifications@github.com wrote:

> http://i.imgur.com/hJcKqSa.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PoomSmart/Emoji83/issues/12#issuecomment-112453384.

## 

_Chris Brown_
_Club Communications Officer_
_Horsford Youth FC_
Like & Follow Us!
[image: 31hdFXk.png?1] http://facebook.com/HorsfordYouthFC [image:
twitter.png] http://twitter.com/HorsfordYouthFC
