### ISSUE TITLE
Misplaced and wrong category icons names.

### ISSUE THREAD

**Issue by shicechi** [PoomSmart/EmojiPort-Legacy#13]
**Emoji9 Fix 1.0-4 tested on an iPhone 6 running iOS 8.4**
- **Category icon highlight displacement**  
  Highlight of selected category icons (grayish circle next to 'ABC' button) is misplaced.
- **Wrong category icons and names**  
  For some categories, the icons are not updated and their names are not consistent with those of the 9.1

**Note**
- According to [this screenshot](https://www.reddit.com/r/jailbreak/comments/3xz49e/release_emoji9_working_ios_91_system_wide/cy9lvic)
- Icon displacement should not present in iOS 9 devices (number of categories was updated)
- Wrong icons and names reproduce in iOS 9 with Emoji9 installed.
- Possible wrong placement for flags category icon (should be the last instead of being second last) on iOS 9 devices.

Screenshots (iOS 8.4 on iPhone 6 vs iOS 9.2 on Simulator):
![comparison](http://i.imgur.com/lCb8hcr.jpg)

**Comment by PoomSmart** [comment]
Fixed. (category name as localization will not be fixed; copyright files issue)
