### ISSUE TITLE
Faulty Eye in Speech Bubble emoji.

### ISSUE THREAD

**Issue by shicechi** [PoomSmart/EmojiPort-Legacy#14]
**Emoji9 Fix 1.0-4 tested on an iPhone 6 running iOS 8.4**

Extensive testing shows that one faulty emoji in Emoji9 is the [👁‍🗨](http://emojipedia.org/eye-in-speech-bubble/).

**Behaviors**
- Inputting this emoji works fine in Spotlight (displayed as one emoji)
- Inputting does not work in Notes.app (disjoint into two emojis)
- Disjoints upon deletion (in Spotlight)
- Needs to press backspace for three times to completely remove (one for eye, one for the joiner, one for speech bubble)
- All of the wrong behaviors above were not reproduced on a jailed iOS 9.2.

**Comment by PoomSmart** [comment]
Is the problem fixed now?

**Comment by shicechi** [comment]
Everything is fixed except that inputting and displaying does not work in apps (disjoint into two emojis).

**Comment by PoomSmart** [comment]
@shicechi The only issue now would be when deleting those new emojis, emoji display has been fixed by EmojiAttributes.

**Comment by shicechi** [comment]
@PoomSmart Confirmed.
