### ISSUE TITLE
[Obsoleted] Emoji9 square emoji issue.

### ISSUE THREAD

**Issue by itFinn** [PoomSmart/EmojiPort-Legacy#15]
Hi, PoomSmart.
I use you develop Emoji9 Legacy & EmojiLayout, have a few problems.
My device is iPhone 6 plus , iOS 8.1

My test mode:
1.  Emoji9 Legacy
2.  EmojiLayout
3.  BytaFont 2
4.  Font -> EmojiOne 2016 Theme(iOS 8) & 
            Emoji Flat Theme (IOS 7-8.1)
![1](http://7xpv2r.com1.z0.glb.clouddn.com/1.png)

Direct use of 1 and 2, appear Emoji have become 口口 bugs.
![2](http://7xpv2r.com1.z0.glb.clouddn.com/2.png)

Direct all , All Emoji have become 口口.
![3](http://7xpv2r.com1.z0.glb.clouddn.com/3.png)

Can you help me fix these bugs?
very thankful , You give the solution.

**Comment by PoomSmart** [comment]
Only one font works at a time. Did you enable font from BytaFont app?

**Comment by itFinn** [comment]
yes, if i did not use font ,i gain a result which can see  it at Photo 2.   if use BytaFont app with only one font .i get result which can see at Photo 3.  so  1. Emoji9 Legacy
2. EmojiLayout still did not work  
 Thx for your message

**Comment by PoomSmart** [comment]
Show me your BytaFont font setting.

**Comment by itFinn** [comment]
I made a total of three tests  

> 1.Only use  
> Emoji9 Legacy  
> EmojiLayout  
> As shown below  
> ![](http://7xpv2r.com1.z0.glb.clouddn.com/1-0.PNG)
> ![](http://7xpv2r.com1.z0.glb.clouddn.com/1-1.PNG)
> ![](http://7xpv2r.com1.z0.glb.clouddn.com/1-2.PNG)  
> Do not use any Font.
> ![](http://7xpv2r.com1.z0.glb.clouddn.com/1-3.PNG)
> ![](http://7xpv2r.com1.z0.glb.clouddn.com/1-4.PNG)  
> Old Emoji Normal display, New Emoji unable to display (Because unused Emoji Fonts)  

---

> 2.USE  
> Emoji9 Legacy  
> EmojiLayout  
> BytaFont 2  
> BytaFont Tweak Mode  
> Emoji Font - > 'EmojiOne 2016 (iOS 8)'    

As shown below  
![](http://7xpv2r.com1.z0.glb.clouddn.com/2-1.PNG)
![](http://7xpv2r.com1.z0.glb.clouddn.com/2-2.PNG)
![](http://7xpv2r.com1.z0.glb.clouddn.com/2-3.PNG)
![](http://7xpv2r.com1.z0.glb.clouddn.com/2-4.PNG)
![](http://7xpv2r.com1.z0.glb.clouddn.com/2-5.PNG)

## ALL Emoji unable to display

> 3.USE  
> Emoji9 Legacy  
> EmojiLayout  
> BytaFont 2  
> BytaFont Tweak Mode  
> Emoji Font - > 'Emoji Flat Theme'  

As shown below  
![](http://7xpv2r.com1.z0.glb.clouddn.com/3-0.PNG)
![](http://7xpv2r.com1.z0.glb.clouddn.com/3-1.PNG)
![](http://7xpv2r.com1.z0.glb.clouddn.com/3-2.PNG)

## ALL Emoji unable to display

**Comment by xfei** [comment]
can you help me ?
