### ISSUE TITLE
Incredibly laggy when installed on iOS 7.1.2 CoolBoot (iPhone 4S)

### ISSUE THREAD

**Issue by Darthagnon** [PoomSmart/EmojiPort-Legacy#16]
I installed EmojiPort7 on my iPhone 4S, running iOS 7.1.2 CoolBoot. I also installed all the dependencies. Due to the large amount of dependencies, I found the easiest way to install them all was to collect all the DEBs, put them in a folder, then "dpkg -i *" to install them all. 

Upon trying to use the Emoji Keyboard, the system lags horribly, and the app in use at the time crashes after a few seconds, though I am able to scroll through the iOS 12.1 emojis (might be able to even type them, but the app usually crashes first).

I tried adjusting settings to no avail. EmojiLayout puts a switch in the wrong place, to switch off the iOS 8.3+ UI. 

I have previously used EmojiPort8 successfully, without any problems, on the same system, when running iOS 8.4.1.

**Comment by Darthagnon** [comment]
The DEBs I installed were:
 - com.ps.emojilayout_1.1.15_iphoneos-arm.deb
 - com.ps.emojiportlegacy_1.7.1_iphoneos-arm.deb
 - com.ps.emojiattributes_1.3.22_iphoneos-arm.deb
 - com.ps.emojifontmanager_0.0.6-1_iphoneos-arm.deb
 - com.ps.emojilibrary_1.0.18.2_iphoneos-arm.deb
 - com.ps.emojilocalization_1.0.11_iphoneos-arm.deb
 - com.ps.emojiresources_1.0.9_iphoneos-arm.deb
 - com.ps.libsubstitrate_0.0.1-3_iphoneos-arm.deb
 - Emoji121_EFM.deb
 - jp.ashikase.libpackageinfo_1.1.0.1-1_iphoneos-arm.deb
 - jp.ashikase.techsupport_1.5.0.1-1_iphoneos-arm.deb
 - ws.hbang.common_1.13.1-2_iphoneos-arm.deb

**Comment by PoomSmart** [comment]
Can you specify the apps that are crashing?

**Comment by Darthagnon** [comment]
Whatsapp, Notes, basically anything with a text input field. If I try to enter text, and I open the emoji keyboard, it lags, then the app CTDs.

**Comment by PoomSmart** [comment]
> Due to the large amount of dependencies, I found the easiest way to install them all was to collect all the DEBs, put them in a folder, then "dpkg -i *" to install them all.

Don't need to queue up every single dependency. Install EmojiPort of your iOS version, EmojiFontManager and the iOS 12.1 emoji font will do.

**Comment by PoomSmart** [comment]
> Whatsapp, Notes, basically anything with a text input field. If I try to enter text, and I open the emoji keyboard, it lags, then the app CTDs.

I cannot reproduce said issues on my iPhone 4s similar to yours.

**Comment by Darthagnon** [comment]
So do I just need the Debs of EmojiFontManager, iOS12.1EFM and Emojiport? 

I'm wondering if maybe there was a conflict with ShowCase or SwipeSelect... Dunno. I'll try installing just those 3 debs from MTerm, see if that works.

**Comment by PoomSmart** [comment]
Well, you can just use Cydia, it will queue up all the dependencies for you.

**Comment by Darthagnon** [comment]
Tried installing just those 3 from Cydia, and disabled all my other substrate addons in iCleaner. Still lags and crashes anything with a text field once I switch to the emoji keyboard :'( 

Ain't installing debs via Cydia and installing those same debs via dpkg and Mterm the same process? Mterm is just more convenient for batch install and not depending on the internet...

**Comment by Darthagnon** [comment]
Anything I can do to get it working?

**Comment by PoomSmart** [comment]
@Darthagnon what’s it like now in 2021 and everything at their latest?

**Comment by Darthagnon** [comment]
Will try it again within the next week or so and let you know :)

**Comment by PoomSmart** [comment]
Stale

**Comment by Darthagnon** [comment]
Guess it's very late, but I finally got around to testing it with everything up-to-date. Switching to emoji keyboard with any textbox selected crashes whatever app it is, or causes a respring if it is on the homescreen search screen.

These are all the auto-installed Emojiport and dependencies that I used (Cydia did not give the option to install just the 3 minimum):
![IMG_0907](https://user-images.githubusercontent.com/20792748/199046491-66bdc488-61fe-409e-b18b-00b06b5b6e58.PNG)

System: iPhone 4S 64GB iOS 7.1.2 (coolbooted from iOS 9.1)
Seems to be incompatible, either with the system or with another tweak (I use 3 other tweaks that affect the keyboard: Eclipse (darkens keyboard), SwipeSelection, and one who's name I don't remember that makes the letter cAsE match on the keyboard)
