### ISSUE TITLE
Bottom bar not responsive in Portrait, until rotated.

### ISSUE THREAD

**Issue by eriksmets** [PoomSmart/EmojiPort-Legacy#3]
iPhone 4S, 8.1.1
emoji83 1.0-22 deb from this repository

On latest version, in Portrait orientation, the bottom Categories bar (including Globe and Delete) initially does not work. It does work in landscape, and after rotating back, it starts working in Portrait.

After switching keyboards to US and back to Emoji, the problem returns, and you have to switch to landscape and back to use the bottom bar in Portrait.

**Comment by Starshooter1996** [comment]
I too have this problem on my iPhone 5s upscaled to iPhone 6 resolution. Hoping this gets fixed soon!

**Comment by Starshooter1996** [comment]
I too have this problem on my iPhone 5s upscaled to iPhone 6 resolution. Hoping this gets fixed soon!

**Comment by jj19** [comment]
I believe this might be a compatibility issue with little brother or any tweak that modifies the resolution (scaling) of iOS... I removed it and started working with no issue.

**Comment by LucasAdam** [comment]
I don't have any scaling / resolution tweak whatsoever but I do have this issue. 
iPhone 5 iOS 8.1.2

**Comment by wowthatisrandom** [comment]
Im on iphone 6 ios 8.1.2 and have same issue, i am NOT using zoom mode

**Comment by jj19** [comment]
This issue is related to predictive keyboard. After turning the predictive keyboard off this issue disappears.

**Comment by eriksmets** [comment]
Fixed in current version 1.0-40
