### ISSUE TITLE
Any app Crashes or cause respring

### ISSUE THREAD

**Issue by jj19** [PoomSmart/EmojiPort-Legacy#4]
Keyboard crashes application when switching to Emojis. Or causes respring on home screen. Emoji83 ver. 1.0-24 + EmojiLayout ver 1.0-7.

**Comment by jj19** [comment]
iPhone 6

**Comment by PoomSmart** [comment]
Send me crash log.
However, this is an issue caused by EmojiLayout. So I will close this issue for Emoji83.
