### ISSUE TITLE
Emoji keyboard "section" selectors unresponsive

### ISSUE THREAD

**Issue by MrAlexWeber** [PoomSmart/EmojiPort-Legacy#5]
Hi, and thanks for your work on this tweak!

I installed the .deb for this and EmojiLayout today and tried them out. EmojiLayout seems to work fine, but Emoji83's updated keyboard was partially unresponsive—the bottom bar with the tabs to select sections didn't respond to touch events, including the "delete" and "change keyboard" keys.

The keyboard itself was responsive, and I was able to type emoji from the initially selected page.

some info about my setup:
- copied emoji font from Mac running Yosemite
- iOS 8.1.2 on iPhone 5 (GSM)

Please let me know if there's any more info I can provide.

**Comment by jj19** [comment]
Try disabling Predictive Text and see if it starts working.

**Comment by wowthatisrandom** [comment]
@jjortiiz this seems to fix the issue thanks. Hopefully @poomsmart can get around that.
